name: Go CI

on:
  push:
    branches: [ "main" , "dev" ]
  pull_request:
    branches: [ "main" , "dev" ]

jobs:
  build-and-test:
    name: Build, Test, Lint and Analyze
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7.0
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli -a root ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.24.x"

    - name: Set Go proxy
      run: echo "GOPROXY=https://goproxy.io,direct" >> $GITHUB_ENV

    - name: Wait for Redis to be ready
      run: |
        for i in {1..10}; do
          if echo "PING" | nc -w 2 localhost 6379 > /dev/null; then
            echo "Redis is ready";
            break;
          fi;
          echo "Waiting for Redis...";
          sleep 3;
        done

    - name: Run vet
      run: make vet

    - name: Run Build and Test via Makefile
      run: |
        make build
        make test
